#!/usr/bin/bash

 echo "[====installing deps====]"

 paru --noconfirm -S hyprland-git dunst bat cava fish kitty neofetch waybar-hyprland-git wofi hyprpaper-git ttf-iosevka-nerd libva qt5-wayland qt5ct nvidia-vaapi-driver-git starship

 paru --noconfirm -S hyprland-git dunst bat cava fish kitty neofetch waybar-hyprland-git wofi hyprpaper-git sddm ttf-iosevka-nerd libva qt5-wayland gt5ct nvidia-vaapi-driver-git starship

 echo "[====moving config====]"

 cp -r ./config/* ~/.config/

 sudo cp -r ./util/cherry-blossom /usr/bin/

 sudo chmod +x /usr/bin/cherry-blossom

 sudo cp -r ./util/cherry-blossom.desktop /usr/share/wayland-sessions/

 echo "[====enabling dm====]"
 
 sudo systemctl disable gdm

 sudo systemctl enable sddm
 
 sudo systemctl disable gdm

 sudo systemctl enable sddm
 
 echo "[====changing shell====]"

 chsh -s /usr/bin/fish 

 chsh -s /usr/bin/fish

 echo "[====done====]"

 echo "you can now logout and login to 'cherry-blossom' desktop ~ and then install windows instead " 
